require 'sinatra'
require 'dotenv/load'
require 'active_record'
require 'sinatra/activerecord'
require_relative '../app/models/suppliers-model'
require_relative '../app/controllers/suppliers-controller'
require_relative '../app/models/material-type-model'